#!/usr/bin/env python3

import argparse
import sys

tasks = {
    'make_config': 'Make template default primer3 config file',
    'batch': 'Run primer3 on a batch of genomes',
    'get_unique': 'Find unique primers, using output of "primer3tools primer3"',
    'version': 'Print version and exit',
}


ordered_tasks = [
    'make_config',
    'batch',
    'get_unique',
    'version'
]


def print_usage_and_exit():
    print('Usage: primer3tools <command> [options] <required arguments>', file=sys.stderr)
    print('\nTo get minimal usage for a command use:\nprimer3tools command', file=sys.stderr)
    print('\nTo get full help for a command use one of:\nprimer3tools command -h\nprimer3tools command --help\n', file=sys.stderr)
    print('\nAvailable commands:\n', file=sys.stderr)
    max_task_length = max([len(x) for x in list(tasks.keys())]) + 1
    for task in ordered_tasks:
        print('{{0: <{}}}'.format(max_task_length).format(task), tasks[task], sep=' ', file=sys.stderr)
    sys.exit(0)

if len(sys.argv) == 1 or sys.argv[1] in ['-h', '-help', '--help']:
    print_usage_and_exit()

task = sys.argv.pop(1)

if task not in tasks:
    print('Task "' + task + '" not recognised. Cannot continue.\n', file=sys.stderr)
    print_usage_and_exit()

exec('import primer3tools.tasks.' + task)
exec('primer3tools.tasks.' + task + '.run()')
